{% set name = "pyrxiv" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrxiv-{{ version }}.tar.gz
  sha256: 7135d209db4a490c3657f3036426b024f98003fc116a4ec316c936124b60040a

build:
  entry_points:
    - pyrxiv = pyrxiv.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.2.1
    - pydantic >=2.10.5,<2.11.dev0
    - structlog >=24.4.0,<24.5.dev0
    - requests >=2.32.4,<2.33.dev0
    - xmltodict >=0.14.2,<0.15.dev0
    - pypdf >=5.7.0,<5.8.dev0
    - pdfminer.six
    - langchain-community >=0.3.27,<0.4.dev0
    - h5py

test:
  imports:
    - pyrxiv
  commands:
    - pip check
    - pyrxiv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JosePizarro3/pyrxiv
  summary: A Python package for retrieving arXiv papers and filter them out with respect to some specific regex pattern.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
